# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Clean node_modules and package-lock.json
      - name: Clean up node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Option 1: Regenerate package-lock.json after cleaning
      - name: Install dependencies and regenerate lock file
        run: npm install --package-lock-only

      # Option 2: Install dependencies conditionally (use npm ci if lockfile exists)
      # - name: Install dependencies
      #   run: |
      #     if [ -f package-lock.json ]; then npm ci; else npm install; fi

      # Build the project
      - name: Build
        run: npm run build

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload build artifacts (dist folder)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
